### ISSUE TITLE
添加微软商店和App Store链接

### ISSUE THREAD

**Issue by frank-782** [scratch-bar/asdm#3]
app store:https://apps.apple.com/cn/app/scratch-desktop/id1446785996?mt=12
ms store:https://www.microsoft.com/zh-cn/p/scratch-3/9pfgj25jl6x3?cid=storebadge&ocid=badge&rtc=1&activetab=pivot:overviewtab

**Comment by waterblock79** [comment]
已添加

![image](https://user-images.githubusercontent.com/33573572/147915382-9a492565-4752-4bc1-ae2f-07bfb6875d60.png)
